# Generated by Django 3.1.6 on 2021-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('descr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
